// Packs the yard models from the Models.codelove.in library (all CC0) into js/yard-models.js.
// The game only reads base colour, so normal / roughness / occlusion maps are dropped and colour
// maps are capped at 512 px (the render engine's largest texture layer). Geometry is unchanged.
//
//   node build_yard.mjs        (from anywhere inside the 3d-models repo: it needs its node_modules)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import { prune, textureCompress } from "@gltf-transform/functions";
import { MeshoptDecoder, MeshoptEncoder } from "meshoptimizer";
import sharp from "sharp";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const LIB = path.resolve(HERE, "../../../../../public/library");
const OUT = path.resolve(HERE, "../../js/yard-models.js");

// key in the game → library file
const PICKS = {
  tree: "avatar-garden/tree02",            // neem and mango trees
  palm: "avatar-garden/base-palm-tree01",  // coconut palm
  banana: "avatar-show/banana-plant",      // banana plants, terrace pots
  tulasi: "avatar-garden/bush03",          // holy basil in the tulasi maadam
  fern: "avatar-garden/bush02",            // ground cover along the walls
  stoneFlat: "avatar-garden/stone01",      // stepping stones
  stone: "avatar-garden/stone02",          // rocks
  deadTree: "halloween-bits/tree-dead-large",
  deadTreeM: "halloween-bits/tree-dead-medium",
  lantern: "halloween-bits/lantern-hanging",
  lanternStand: "halloween-bits/lantern-standing",
};

await MeshoptDecoder.ready;
await MeshoptEncoder.ready;
const io = new NodeIO()
  .registerExtensions(ALL_EXTENSIONS)
  .registerDependencies({ "meshopt.decoder": MeshoptDecoder, "meshopt.encoder": MeshoptEncoder });

const lines = [
  "// Yard models from the Models.codelove.in library (https://models.codelove.in), all CC0.",
  "// Generated by assets-src/yard/build_yard.mjs: do not edit by hand.",
  "window.YARD_GLB = {",
];
let total = 0;
for (const [key, file] of Object.entries(PICKS)) {
  const doc = await io.read(path.join(LIB, file + ".glb"));
  for (const m of doc.getRoot().listMaterials()) {
    m.setNormalTexture(null).setOcclusionTexture(null).setMetallicRoughnessTexture(null).setEmissiveTexture(null);
    for (const ext of m.listExtensions()) ext.dispose(); // specular / ior: unused here
  }
  await doc.transform(prune(), textureCompress({ encoder: sharp, targetFormat: "webp", resize: [512, 512], quality: 88 }));
  const glb = Buffer.from(await io.writeBinary(doc));
  total += glb.length;
  console.log(key.padEnd(13), file.padEnd(34), (glb.length / 1024).toFixed(0).padStart(4), "KB");
  lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(glb.toString("base64"))},`);
}
lines.push("};", "");
fs.writeFileSync(OUT, lines.join("\n"));
console.log("total", (total / 1024).toFixed(0), "KB →", path.relative(process.cwd(), OUT));
