import type { GameEntry } from "@/lib/games";

/** Kingdom Clash — every model it uses, from the site's own library (public/library). No three.js here. */

const town = (n: string) => `fantasy-town-kit/${n}`;
const castle = (n: string) => `castle-kit/${n}`;
const td = (n: string) => `tower-defense-kit/${n}`;
const surv = (n: string) => `survival-kit/${n}`;
const nat = (n: string) => `nature-kit/${n}`;
const dun = (n: string) => `mini-dungeon/${n}`;
const grave = (n: string) => `graveyard-kit/${n}`;
const mini = (n: string) => `mini-characters/${n}`;

/** Short names for every model (buildings are composed from these in recipes.ts). */
export const K = {
  // Fantasy Town Kit
  wall: town("wall"),
  wallDoor: town("wall-door"),
  wallWindow: town("wall-window-shutters"),
  wallWindowGlass: town("wall-window-glass"),
  wallWood: town("wall-wood"),
  wallWoodDoor: town("wall-wood-door"),
  wallWoodWindow: town("wall-wood-window-shutters"),
  roofPoint: town("roof-point"),
  roofHighPoint: town("roof-high-point"),
  roofHighGable: town("roof-high-gable"),
  roofGable: town("roof-gable"),
  chimney: town("chimney"),
  bannerRed: town("banner-red"),
  bannerGreen: town("banner-green"),
  lantern: town("lantern"),
  fountain: town("fountain-round"),
  fountainDetail: town("fountain-round-detail"),
  cartHigh: town("cart-high"),
  windmillBlades: town("windmill"),
  watermill: town("watermill"),
  stallRed: town("stall-red"),
  pillarStone: town("pillar-stone"),
  pillarWood: town("pillar-wood"),
  hedge: town("hedge-large"),
  planks: town("planks"),
  overhang: town("overhang"),
  townTree: town("tree-high-round"),
  // Castle Kit
  towerBase: castle("tower-square-base"),
  towerBaseColor: castle("tower-square-base-color"),
  towerBorder: castle("tower-square-base-border"),
  towerMidDoor: castle("tower-square-mid-door"),
  towerMidWindows: castle("tower-square-mid-windows"),
  towerMid: castle("tower-square-mid"),
  towerTopRoof: castle("tower-square-top-roof"),
  towerTopRoofWindows: castle("tower-square-top-roof-high-windows"),
  towerTopRoofHigh: castle("tower-square-top-roof-high"),
  towerTop: castle("tower-square-top"),
  hexBase: castle("tower-hexagon-base"),
  hexMid: castle("tower-hexagon-mid"),
  hexRoof: castle("tower-hexagon-roof"),
  roundTower: castle("tower-base"),
  roundTop: castle("tower-top"),
  flag: castle("flag"),
  flagWide: castle("flag-wide"),
  flagPennant: castle("flag-pennant"),
  bannerLong: castle("flag-banner-long"),
  bannerShort: castle("flag-banner-short"),
  castleWallNarrow: castle("wall-narrow"),
  castleWallPillar: castle("wall-pillar"),
  gate: castle("gate"),
  siegeCatapult: castle("siege-catapult"),
  siegeCatapultBroken: castle("siege-catapult-demolished"),
  rocksLarge: castle("rocks-large"),
  rocksSmall: castle("rocks-small"),
  // Tower Defense Kit
  tdRoundBase: td("tower-round-base"),
  tdRoundBottomA: td("tower-round-bottom-a"),
  tdRoundBottomB: td("tower-round-bottom-b"),
  tdRoundBottomC: td("tower-round-bottom-c"),
  tdRoundMiddleA: td("tower-round-middle-a"),
  tdRoundMiddleB: td("tower-round-middle-b"),
  tdRoundTopA: td("tower-round-top-a"),
  tdRoundTopB: td("tower-round-top-b"),
  tdRoundRoofA: td("tower-round-roof-a"),
  tdRoundCrystals: td("tower-round-crystals"),
  tdSquareBottomA: td("tower-square-bottom-a"),
  tdSquareBottomB: td("tower-square-bottom-b"),
  tdSquareMiddleA: td("tower-square-middle-a"),
  tdSquareMiddleB: td("tower-square-middle-b"),
  tdSquareTopA: td("tower-square-top-a"),
  tdSquareRoofA: td("tower-square-roof-a"),
  woodStructure: td("wood-structure"),
  woodStructureHigh: td("wood-structure-high"),
  woodPart: td("wood-structure-high-part"),
  cannon: td("weapon-cannon"),
  ballista: td("weapon-ballista"),
  turret: td("weapon-turret"),
  cannonball: td("weapon-ammo-cannonball"),
  arrow: td("weapon-ammo-arrow"),
  boulder: td("weapon-ammo-boulder"),
  crystal: td("detail-crystal"),
  crystalLarge: td("detail-crystal-large"),
  selection: td("selection-a"),
  // Survival Kit
  goldOre: surv("resource-stone-large"),
  stone: surv("resource-stone"),
  logs: surv("tree-log"),
  boxLarge: surv("box-large"),
  barrelSmall: surv("barrel"),
  tent: surv("tent-canvas"),
  campfire: surv("campfire-pit"),
  anvil: surv("workbench-anvil"),
  workbench: surv("workbench"),
  fence: surv("fence-fortified"),
  trunk: surv("tree-trunk"),
  hammer: surv("tool-hammer"),
  rockB: surv("rock-b"),
  // Nature Kit
  treeOak: nat("tree-oak"),
  treeDefault: nat("tree-default"),
  treeFat: nat("tree-fat"),
  treeDetailed: nat("tree-detailed"),
  treePineRound: nat("tree-pine-round-a"),
  treePineTall: nat("tree-pine-tall-a"),
  treeCone: nat("tree-cone"),
  treeFall: nat("tree-default-fall"),
  rockLarge: nat("rock-large-a"),
  stoneTall: nat("stone-tall-a"),
  bush: nat("plant-bush-large"),
  stump: nat("stump-round"),
  mushrooms: nat("mushroom-red-group"),
  flowers: nat("flower-red-a"),
  // Mini Dungeon / Forest / Arena / Graveyard props
  potion: dun("potion"),
  coin: dun("coin"),
  chest: dun("chest"),
  keg: dun("barrel"),
  spikes: dun("trap"),
  sword: dun("weapon-sword"),
  shieldRound: dun("shield-round"),
  shieldRect: dun("shield-rectangle"),
  key: dun("key"),
  bow: "mini-forest/weapon-bow",
  target: "mini-forest/target",
  forestTent: "mini-forest/tent",
  weaponRack: "mini-arena/weapon-rack",
  statue: "mini-arena/statue",
  spear: "mini-arena/weapon-spear",
  arenaBanner: "mini-arena/banner",
  debris: grave("debris"),
  debrisWood: grave("debris-wood"),
  fireBasket: grave("fire-basket"),
  lanternGlass: grave("lantern-glass"),
  obelisk: grave("pillar-obelisk"),
  altar: grave("altar-stone"),
  gravestone: grave("gravestone-round"),
  stoneWall: grave("stone-wall"),
  brickWall: grave("brick-wall"),
  graveMound: grave("grave"),
  // God of War collection: the frost axe and chaos blade (hero / troop gear)
  frostAxe: "god-of-war/leviathan-axe",
  chaosBlade: "god-of-war/blades-of-chaos",
  // Characters
  warrior: "mini-arena/character-soldier",
  archer: "mini-forest/character-archer",
  giant: "mini-dungeon/character-orc",
  breaker: mini("character-male-b"),
  mage: mini("character-female-e"),
  thief: mini("character-female-f"),
  healer: mini("character-female-d"),
  builder: mini("character-male-d"),
  skeleton: grave("character-skeleton"),
  zombie: grave("character-zombie"),
  vampire: grave("character-vampire"),
  keeper: grave("character-keeper"),
  // Heroes and the Skeleton Trap's skeletons
  king: "character-pack-adventures/barbarian",
  queen: "god-of-war/spartan-archer",
  bones: "god-of-war/spartan-warrior",
} as const;

export type ModelName = keyof typeof K;

/** Raiders, heroes and trap skeletons only matter later: loaded after the first screen. */
export const LATE: ModelName[] = ["skeleton", "zombie", "vampire", "keeper", "king", "queen", "bones"];

/** Load order matters: the village (buildings, then troops) first, raiders last. */
export const MODELS: string[] = [
  ...(Object.keys(K) as ModelName[]).filter((n) => !LATE.includes(n)).map((n) => K[n]),
  ...LATE.map((n) => K[n]),
];

export const GAME: GameEntry = {
  slug: "kingdom-clash",
  title: "Kingdom Clash",
  tagline: "Build your village, train an army, raid 100 rival villages.",
  description:
    "A 3D base-building strategy game. Name your village and grow it around the Town Hall: gold mines and elixir collectors, storages, barracks, army camps, a laboratory and a spell factory, hero altars, cannons, archer towers, catapults, mage towers, bomb and skeleton traps and walls — Town Hall and every building upgradeable to level 5. Train warriors, archers, thieves, giants, wall breakers, mages and healers who march to your army camps, lead them with the Axe King and the Elf Queen, brew lightning, heal, rage, freeze and jump spells, then raid a 100-stage campaign of enemy villages to steal their gold and elixir — and hold the line when raiders come for yours.",
  genre: "Base-building strategy",
  accent: "#fbbf24",
  cover: "/games/kingdom-clash/cover.webp",
  models: MODELS,
  collections: ["Fantasy Town Kit", "Castle Kit", "Tower Defense Kit", "Survival Kit", "Nature Kit", "Mini Dungeon", "Mini Characters", "Graveyard Kit", "Character Pack Adventures"],
  controls: [
    { action: "Select / place / collect", keys: ["Click"], touch: "Tap" },
    { action: "Move a selected building", keys: ["Drag"], touch: "Drag it" },
    { action: "Pan / zoom", keys: ["W A S D", "Wheel"], touch: "Drag / pinch" },
    { action: "Upgrade selected building", keys: ["U"], touch: "Upgrade button" },
    { action: "Shop / army / raid", keys: ["B", "T", "R"], touch: "Bottom buttons" },
    { action: "Collect all resources", keys: ["C"], touch: "Collect bubbles" },
    { action: "Pick troop or spell in battle", keys: ["1–9"], touch: "Hotbar" },
    { action: "Hero ability (hero on the field)", keys: ["Hero's number"], touch: "Tap the hero again" },
    { action: "Deploy troops / cast spells", keys: ["Click", "Hold"], touch: "Tap outside the red zone" },
  ],
  howTo: [
    "Gold Mines and Elixir Collectors fill up over time — tap their bubbles to collect. Storages raise how much you can hold.",
    "Builders work on one construction at a time. Upgrade the Town Hall to unlock new buildings, more copies and higher levels (everything goes to level 5).",
    "Defences, walls and the Town Hall cost gold; barracks, camps, the laboratory, the spell factory, troops and spells cost elixir.",
    "Train troops in the Barracks — they march to the Army Camps and wait around the campfire. Research stronger troops and spells in the Laboratory.",
    "Build the King's Altar (Town Hall 3) and the Queen's Altar (Town Hall 4). Heroes join every raid once, tap them again for War Cry or Vanish, guard your village — and sleep at their altar to heal.",
    "Raid the 100-stage campaign: tap outside the red zone to drop troops. 50% destroyed = 1 star, Town Hall = 1 star, 100% = 3 stars. Every attack steals gold and elixir — farm any stage again.",
    "Raiders attack your village now and then: defences fight on their own, and you can drop your troops inside your walls to help.",
  ],
  features: ["Town Hall, buildings, defences & troops up to level 5", "Axe King & Elf Queen heroes with abilities", "100-stage raid campaign with stars", "Steal gold & elixir, farm any stage again", "Spells: lightning, heal, rage, freeze, jump", "Skeleton traps, bombs & walls to defend your village"],
  // Recorded tracks (soundtrack.ts), CC BY 4.0 — the full credit is in the game's Settings.
  music: "Thatched Villagers & Clash Defiant by Kevin MacLeod (CC BY 4.0)",
};
