import { TextLink, TextList, TextPage, TextSection } from "@/components/text-page";
import { pageMetadata } from "@/lib/seo";
import { SITE } from "@/lib/site";

export const metadata = pageMetadata({
  title: "Terms of Use",
  description: `The terms for using ${SITE.name}: the site, its tools and its games are free and provided as is, and every 3D model comes with its own open license — MIT, CC0, public domain or CC BY.`,
  path: "/terms/",
});

/** Change this date whenever the terms change. What a model's license allows is on /license/ — don't restate it here. */
const UPDATED = "2026-10-10";

export default function TermsPage() {
  return (
    <TextPage
      eyebrow="Terms"
      title="Terms of Use"
      updated={UPDATED}
      intro={
        <>
          {SITE.name} is free to use and needs no account. These terms cover the site itself. What you may do with a 3D model
          you download is set by that model&apos;s own license, not by this page.
        </>
      }
    >
      <TextSection id="agreement" title="Using the site">
        <p>
          By using {SITE.name} you agree to these terms. If you do not agree with them, please do not use the site. &quot;We&quot; and
          &quot;us&quot; mean {SITE.author}, who makes and runs it.
        </p>
      </TextSection>

      <TextSection id="models" title="The 3D models and their licenses">
        <p>
          Every model, pack and animation clip is offered under an open license: the MIT License, CC0, public domain, or — for a
          few hairstyles — CC BY or CC BY-ND. Each model page names its license, and the license travels with every download.
          The <TextLink href="/license/">Licensing</TextLink> page has the full texts and explains how to credit an author.
        </p>
        <TextList>
          <li>That license, not these terms, decides what you may do with a downloaded file.</li>
          <li>
            Following it is up to you: keep the copyright notice with MIT-licensed files, credit the author of CC BY models, and
            share CC BY-ND models only unmodified.
          </li>
          <li>
            A license to a 3D file covers the file. It does not give you trademark or other rights in what the model shows — a
            logo or insignia, a brand name, or a recognizable character or person. If your project depends on those, check that
            you may use them.
          </li>
        </TextList>
        <p>
          You may load models, thumbnails and the catalog files straight from this site in your own project, as described on{" "}
          <TextLink href="/developers/">For developers &amp; AI</TextLink>.
        </p>
      </TextSection>

      <TextSection id="site-content" title="The site, its tools and its games">
        <p>
          The site&apos;s own text, design and code, and the games on it, belong to their author. You are welcome to play the games
          and use the viewer and the scene builder for free, for any purpose. Please do not copy or republish the site itself
          or its games without asking first.
        </p>
        <p>
          What you make stays yours: a file you open in the viewer and a scene you build are handled in your browser and are
          not uploaded to us. A scene you export contains models from the library, and their licenses still apply to it.
        </p>
        <p>
          AI scenes in the scene builder are generated by Google&apos;s Gemini API with your own API key, so Google&apos;s terms for
          that service apply to your use of it, and the results may not be what you asked for.
        </p>
      </TextSection>

      <TextSection id="conduct" title="Fair use of the site">
        <TextList>
          <li>Do not use the site to break the law or to infringe anyone&apos;s rights.</li>
          <li>Do not try to break, overload or get around the security of the site or the services behind it.</li>
          <li>
            In online games, pick a name that is not offensive and does not give away who you are, and do not spoil the game for
            other players.
          </li>
          <li>Do not present the site, or anything you make with it, as endorsed by us or by a model&apos;s author.</li>
        </TextList>
      </TextSection>

      <TextSection id="copyright" title="Copyright complaints">
        <p>
          We publish models only under the licenses named above, and we want credits and licenses to be right. If you believe
          a model, or anything else on the site, uses your work without permission or carries the wrong credit or license,
          write to <TextLink href={`mailto:${SITE.email}`}>{SITE.email}</TextLink> with:
        </p>
        <TextList>
          <li>the address of the page it is on;</li>
          <li>what the work is and how we can tell it is yours;</li>
          <li>what you would like us to do — correct the credit or license, or remove it.</li>
        </TextList>
        <p>We will look into it and correct or remove what should not be here.</p>
      </TextSection>

      <TextSection id="advertising" title="Advertising and other sites">
        <p>
          The site is free, and it may show advertising to help pay for hosting. The{" "}
          <TextLink href="/privacy/">Privacy Policy</TextLink> explains how that works and how to opt out of personalized ads.
        </p>
        <p>
          Pages may link to sites we do not run, such as an author&apos;s page or a license text. We are not responsible for what is
          on them.
        </p>
      </TextSection>

      <TextSection id="warranty" title="No warranty">
        <p>
          The site, the models, the tools and the games are provided &quot;as is&quot;, without warranties of any kind. We do not
          promise that a model suits your purpose, that a file opens in your software, that the site is always available, or
          that everything on it is free of errors. Saves and projects kept in your browser can be lost if its data is cleared —
          export what you want to keep.
        </p>
      </TextSection>

      <TextSection id="liability" title="Limits of liability">
        <p>
          As far as the law allows, we are not liable for any loss or damage that comes from using the site, or from using —
          or not being able to use — anything downloaded from it. Nothing in these terms takes away rights that the law gives
          you and that cannot be given up.
        </p>
      </TextSection>

      <TextSection id="changes" title="Changes">
        <p>
          The site changes often: models, tools and games may be added, changed or removed. If these terms change, this page
          and the date at the top change with them, and the new terms apply from then on.
        </p>
      </TextSection>

      <TextSection id="contact" title="Contact">
        <p>
          Questions about these terms: <TextLink href={`mailto:${SITE.email}`}>{SITE.email}</TextLink>, or see{" "}
          <TextLink href="/contact/">Contact</TextLink>.
        </p>
      </TextSection>
    </TextPage>
  );
}
