import type { GameEntry } from "@/lib/games";

/** Nova Strike — every model it uses, from the site's own library (public/library). No three.js here. */

/** Model keys by role. */
export const M = {
  // Ships (Space Kit crafts face -Z).
  player: "space-kit/craft-racer",
  speederA: "space-kit/craft-speeder-a",
  speederB: "space-kit/craft-speeder-b",
  speederC: "space-kit/craft-speeder-c",
  speederD: "space-kit/craft-speeder-d",
  cargoA: "space-kit/craft-cargo-a",
  cargoB: "space-kit/craft-cargo-b",
  miner: "space-kit/craft-miner",
  // Rocks.
  meteor: "space-kit/meteor",
  meteorDetailed: "space-kit/meteor-detailed",
  rockA: "space-kit/rock-large-a",
  rockB: "space-kit/rock-large-b",
  crystalA: "space-kit/rock-crystals-large-a",
  crystalB: "space-kit/rock-crystals-large-b",
  // Hardware.
  turretSingle: "space-kit/turret-single",
  turretDouble: "space-kit/turret-double",
  dish: "space-kit/satellite-dish-large",
  structure: "space-kit/structure",
  structureClosed: "space-kit/structure-closed",
  structureDiagonal: "space-kit/structure-diagonal",
  supports: "space-kit/supports-high",
  platformHigh: "space-kit/platform-high",
  gateComplex: "space-kit/gate-complex",
  generator: "space-kit/machine-generator-large",
  hangarGlass: "space-kit/hangar-round-glass",
  pipe: "space-kit/pipe-straight",
  pipeRing: "space-kit/pipe-ring-high",
  rocketTop: "space-kit/rocket-top-b",
  rifle: "space-kit/weapon-rifle",
  // Station trench (Space Station Kit + Modular Space Kit).
  wall: "space-station-kit/wall",
  wallWindow: "space-station-kit/wall-window",
  wallPillar: "space-station-kit/wall-pillar-banner",
  floor: "space-station-kit/floor-panel-straight",
  floorDetail: "space-station-kit/floor-detail",
  barrier: "space-station-kit/structure-barrier",
  container: "space-station-kit/container-tall",
  display: "space-station-kit/display-wall-wide",
  laserGate: "modular-space-kit/gate-lasers",
  // NASA hardware, drones and backdrops.
  mgs: "planets/mars-global-surveyor",
  wfpc: "planets/wide-field-planetary-camera",
  mro: "planets/mars-reconnaissance-orbiter-mro-b",
  rover: "planets/mars-exploration-rover-opportunity-mer-b",
  bennu: "planets/1999-rq36-asteroid",
  jupiterC: "planets/explorer-jupiter-c-rocket",
  mir: "satellites/mir",
  tdrs: "satellites/tracking-and-data-relay-tdrs-a",
  grace: "satellites/gravity-recovery-and-climate-experiment-grace-a",
  seastar: "satellites/sea-star",
  drone: "crystal-crossroads/sci-fi-drone",
  stardust: "avatar-garden/planet-stardust01",
  ringedPlanet: "towers/colony-planet-art",
  pinkPlanet: "towers/colony-planet-02-art",
} as const;

/** Load order matters: what the first screen needs goes first. */
export const MODELS: string[] = [
  M.player,
  M.ringedPlanet,
  M.bennu,
  M.meteor,
  M.meteorDetailed,
  M.rockA,
  M.rockB,
  M.crystalA,
  M.crystalB,
  M.stardust,
  M.speederA,
  M.speederB,
  M.speederC,
  M.speederD,
  M.cargoA,
  M.cargoB,
  M.miner,
  M.turretSingle,
  M.turretDouble,
  M.rocketTop,
  M.rifle,
  M.dish,
  M.structure,
  M.structureClosed,
  M.structureDiagonal,
  M.supports,
  M.platformHigh,
  M.gateComplex,
  M.generator,
  M.hangarGlass,
  M.pipe,
  M.pipeRing,
  M.pinkPlanet,
  M.mgs,
  M.wfpc,
  M.mro,
  M.rover,
  M.jupiterC,
  M.mir,
  M.tdrs,
  M.grace,
  M.seastar,
  M.drone,
  M.wall,
  M.wallWindow,
  M.wallPillar,
  M.floor,
  M.floorDetail,
  M.barrier,
  M.container,
  M.display,
  M.laserGate,
];

export const GAME: GameEntry = {
  slug: "nova-strike",
  title: "Nova Strike",
  tagline: "Barrel-roll through asteroids, drones and a space-station trench.",
  description:
    "A 3D on-rails space shooter. Fly a racer through an asteroid belt, a graveyard of drifting NASA satellites and a space-station trench, blasting drones and turrets, barrel-rolling through fire and locking on with charged shots — then take down each stage's boss.",
  genre: "Rail shooter",
  accent: "#22d3ee",
  cover: "/games/nova-strike/cover.webp",
  models: MODELS,
  collections: ["Space Kit", "Space Station Kit", "Modular Space Kit", "Planets & Small Bodies", "Satellites & Probes", "Crystal Crossroads", "Avatar Garden", "Towers"],
  controls: [
    { action: "Fly", keys: ["W", "A", "S", "D", "Arrows"], touch: "Left stick" },
    { action: "Fire (hold to charge a lock-on)", keys: ["Space", "J", "Click"], touch: "FIRE button (hold to charge)" },
    { action: "Barrel roll", keys: ["Q", "E"], touch: "ROLL button" },
    { action: "Boost", keys: ["Shift"], touch: "BOOST button (hold)" },
    { action: "Brake", keys: ["C"] },
    { action: "Nova bomb", keys: ["B"], touch: "Bomb button" },
  ],
  howTo: [
    "Your ship flies forward on its own — steer to dodge rocks and shoot everything in your way.",
    "Tap fire for lasers. Hold it to charge: sweep the reticle over up to 4 targets, then let go to fire homing shots.",
    "A barrel roll (Q / E) knocks enemy shots away for a moment — roll through a volley.",
    "Fly through golden rings to repair your shield. Nova bombs (B) clear the screen — save them for bosses.",
    "Every stage ends with a boss: watch for the warning glow, then hit the glowing weak points.",
    "Chain kills quickly for a combo multiplier, and destroy most of a stage for a gold medal.",
  ],
  touchHowTo: [
    "Your ship flies forward on its own — drag on the left half of the screen to steer, dodge rocks and shoot everything in your way.",
    "Tap FIRE for lasers. Hold it until its ring fills to charge, steer the ship's nose over up to 4 targets, then let go to fire homing shots.",
    "Tap ROLL for a barrel roll — it knocks enemy shots away for a moment, so roll through a volley.",
    "Fly through golden rings to repair your shield. The bomb button fires a nova bomb that clears the screen — save them for bosses.",
    "Every stage ends with a boss: watch for the warning glow, then hit the glowing weak points.",
    "Chain kills quickly for a combo multiplier, and destroy most of a stage for a gold medal.",
  ],
  features: ["3 stages + bosses", "Barrel rolls & lock-on shots", "Asteroids, NASA satellites & a station trench", "Medals, combos & a high score table"],
  music: "Nova Rush",
  comingSoon: true,
};
